apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sbe-gateway-service
  namespace: sbe-gateway-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sbe-gateway-service  # Corrected to match the deployment name
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale up when CPU usage exceeds 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60  # Scale up when memory usage exceeds 60%

